---
- hosts: all
  vars_files:
  - azure_cluster.yml
  become: true
  roles:
    - ottar63.docker
  tasks:
    - name: Install Python tools
      apt:
        name:
          - python-setuptools
          - python-pip
        state: present

    - name: install  docker python library
      pip:
        name:
          - docker-py
          - jsondiff
          - pyyaml

    - name: Set Broadcast IP
      set_fact:
        broadcast_ip: "{{azure_hosts[ansible_hostname].private_ip}}"
      when: ansible_hostname == manager_host

    - name: Start docker swarm on master
      docker_swarm:
        advertise_addr: "{{broadcast_ip}}"
        state: present
      register: swarm_out
      when: ansible_hostname == manager_host

    - name: Set join Toke
      set_fact:
        join_token: "{{swarm_out.swarm_facts.JoinTokens.Worker}}"
      when: ansible_hostname == manager_host

    - name: Join nodes to swarm
      docker_swarm:
        state: join
        remote_addrs: "{{hostvars[manager_host].broadcast_ip}}"
        join_token: "{{hostvars[manager_host].join_token}}"
        advertise_addr: "{{azure_hosts[ansible_hostname].private_ip}}"
      when: azure_hosts[ansible_hostname].hostname != manager_host
