---
- hosts: localhost
  connection: local
  vars:
    pub_key: "{{lookup('file','~/.ssh/id_rsa.pub')}}"
    docker_user: "{{lookup('env','USER')}}"
  vars_files:
    - azure_cluster.yml
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{resourcegroup}}"
        location: eastus
      register: rg

    - name: Create Security group for demo app
      azure_rm_securitygroup:
        resource_group: "{{resourcegroup}}"
        name: "{{securitygroup}}"
        rules:
          - name: Vote
            protocol: Tcp
            destination_port_range: 5000
            access: Allow
            priority: 103
            direction: Inbound

          - name: Result
            protocol: Tcp
            destination_port_range: 5001
            access: Allow
            priority: 104
            direction: Inbound

          - name: Viz
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 105
            direction: Inbound

          - name: SSH_Allow
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 102
            direction: Inbound
            source_address_prefix:
              - "193.91.144.138/32"
      register: votegrp

    - name: Create Virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{resourcegroup}}"
        name: "{{virtualnet}}"
        address_prefixes: "10.10.0.0/16"

    - name: Create Subnet
      azure_rm_subnet:
        resource_group: "{{resourcegroup}}"
        name: "{{subnet}}"
        virtual_network: virtualnet
        address_prefix: "10.10.0.0/24"

    - name: Create Subnet for external
      azure_rm_subnet:
        resource_group: "{{resourcegroup}}"
        name: "{{subnet_ext}}"
        virtual_network: virtualnet
        address_prefix: "10.10.1.0/24"

    - name: Create Storage
      azure_rm_storageaccount:
        resource_group: "{{resourcegroup}}"
        name: ansibleaccount001
        account_type: Standard_LRS

    - include_tasks: create_vm.yml
      vars:
        host: "{{azure_hosts[item]}}"
      with_items: "{{azure_hosts}}"

    - name: Debug publicip
      debug:
        msg: "{{publicip}}"

    - name: Debug azure_hosts
      debug:
        msg: "{{azure_hosts[item].hostname}}"
      with_items: "{{azure_hosts}}"

    - name: Create/update ssh config
      blockinfile:
        path: ~/.ssh/config
        create: "yes"
        block: |
          StrictHostKeyChecking no
          Host    "{{azure_hosts[item].hostname}}"
          ProxyCommand ssh -W %h:%p "{{docker_user}}@{{public_ip}}"
          UserKnownHostsFile /dev/null
        marker: "#  {mark} hostname: {{azure_hosts[item].hostname}}  "
      with_items: "{{azure_hosts}}"
